### ISSUE TITLE
Drop down not always showing

### ISSUE THREAD

**Issue by pfelsted** [Brandply/publicissues#16]
We need to try and reproduce and add more details.
Customer: Levine Shosh iheartmedia

·         Most had the drop down feature to save the icon on the mobile page--- however not everyone got this (do you know why this could be?)

**Comment by brandplysreese** [comment]
We use a script called "add to homescreen" for this functionality. 
Here is a link to its github:
https://github.com/cubiq/add-to-homescreen

The script is currently Compatible with iOS 6+ and Chrome for Android (soon WinPhone).
![screen shot 2015-08-10 at 8 47 49 pm](https://cloud.githubusercontent.com/assets/12085564/9187682/36cbff36-3fa1-11e5-82b9-6d1182a76162.png)

In order to support more browsers we would either need to modify the script ourselves, which would require us to know exactly what browsers we are going to add support for and do extensive testing for each browser and device, or we can try and find a different script that supports our required browsers.

**Comment by pfelsted** [comment]
We will no fix this we think the client can upgrade their browser, Stu will talk to the client.

**Comment by pfelsted** [comment]
This needs some investigation so that we can get this working on all browsers.

**Comment by brandplysreese** [comment]
This issue was moved to Brandply/brandply#410
